version: "2"
services:
  360-image:
    image: 360-viewer-image:latest
    container_name: 360-viewer
    volumes:
      - 360-viewer-volume:/360-viewer
    ports:
      - "4354:5000"

volumes:
  360-viewer-volume:
    external: true
